/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ListFilterBar: typeof import('./src/components/ListFilterBar.vue')['default']
    ListPagination: typeof import('./src/components/ListPagination.vue')['default']
    PdfAttachmentActions: typeof import('./src/components/PdfAttachmentActions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SortableColumn: typeof import('./src/components/SortableColumn.vue')['default']
  }
}
